version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  shopcatalogservice:
    image: josephpatricio/shopcatalogservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

volumes:
  mongodbdata:
