apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: shopcatalogservice
  name: shopcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopcatalogservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: shopcatalogservice
    spec:
      containers:
        - image: josephpatricio/shopcatalogservice
          name: shopcatalogservice
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
